# Generated by Django 4.0.4 on 2022-06-05 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('status', models.CharField(choices=[('new', 'New'), ('todo', 'ToDo'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=64, verbose_name='status')),
                ('admin_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('text_todo', models.TextField(verbose_name='text')),
                ('status', models.CharField(choices=[('new', 'New'), ('todo', 'ToDo'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=64, verbose_name='status')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='start')),
                ('end_date', models.DateTimeField(verbose_name='end')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='todo_app.project')),
                ('team_member', models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
