# Generated by Django 4.0.4 on 2022-06-15 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin_todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('todo', 'ToDo'), ('completed', 'Completed'), ('archived', 'Archived')], default='new', max_length=64, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('todo', 'ToDo'), ('completed', 'Completed'), ('archived', 'Archived')], default='new', max_length=64, verbose_name='status'),
        ),
    ]
