# Generated by Django 4.0.4 on 2022-06-25 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0002_alter_project_admin_todo_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin_todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_member',
            field=models.ManyToManyField(related_name='project_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='todo_app.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_member',
            field=models.ManyToManyField(related_name='task_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
