# Generated by Django 4.0.4 on 2022-06-25 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0003_alter_project_admin_todo_alter_project_team_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team_member',
            field=models.ManyToManyField(blank=True, related_name='task_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
